basePath: /
definitions:
  models.Device:
    properties:
      client_details:
        items:
          properties:
            can_get_sms:
              type: boolean
            email:
              type: string
            name:
              type: string
            phone:
              type: string
          type: object
        type: array
      created_at:
        type: string
      created_by_email:
        type: string
      created_by_id:
        type: string
      device_address:
        type: string
      device_alias:
        type: string
      geolocation:
        properties:
          lat:
            type: string
          lon:
            type: string
        type: object
      group_id:
        type: string
      group_name:
        type: string
      has_geolocation_data:
        type: boolean
      id:
        type: string
      is_deployed:
        type: boolean
      location_id:
        type: string
      location_name:
        type: string
      owner_id:
        type: string
      owner_name:
        type: string
      physical_location:
        type: string
      sensor_class_id:
        type: string
      sensor_class_name:
        type: string
      sensor_type_id:
        type: string
      sensor_type_name:
        type: string
      updated_at:
        type: string
    type: object
  utils.HTTPError:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: info@teleops.io
    name: API Support
  description: Teleops IOT server API
  title: Teleops  API
  version: "2.0"
paths:
  /api/devices/:
    get:
      consumes:
      - application/json
      description: Get all Devices
      operationId: get-item-by-int
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Device'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Get all Devices
      tags:
      - Devices End Points
  /api/devices/create:
    post:
      consumes:
      - application/json
      description: Create a device
      operationId: create-device
      parameters:
      - description: Device details
        in: body
        name: device
        required: true
        schema:
          $ref: '#/definitions/models.Device'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Device'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Create a device
      tags:
      - Devices End Points
swagger: "2.0"
